version: '3.2'
volumes:
  app:

services:
  &app-service app:
    image: dralec/php73-cli-alpine-debug
    hostname: *app-service
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/var/www
    environment:
      DOCKER_TERM: "${TERM:-}"      # pass host $TERM variable
      COLORTERM: "${COLORTERM:-}"   # pass host $COLORTERM variable
    command: keep-alive.sh
