var classes = [
    {
        "name": "AlecRabbit\\Themed",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setDefaultThemes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "comment",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "yellow",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "red",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "info",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "green",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dark",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "AlecRabbit\\ConsoleColour",
            "AlecRabbit\\Contracts\\ThemesInterface",
            "parent",
            "parent"
        ],
        "parents": [
            "AlecRabbit\\ConsoleColour"
        ],
        "lcom": 1,
        "length": 48,
        "vocabulary": 12,
        "volume": 172.08,
        "difficulty": 6.33,
        "effort": 1089.83,
        "level": 0.16,
        "bugs": 0.06,
        "time": 61,
        "intelligentContent": 27.17,
        "number_operators": 10,
        "number_operands": 38,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 46,
        "loc": 96,
        "lloc": 50,
        "mi": 90.8,
        "mIwoC": 46.88,
        "commentWeight": 43.92,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.8,
        "relativeSystemComplexity": 17.8,
        "totalStructuralComplexity": 144,
        "totalDataComplexity": 16.2,
        "totalSystemComplexity": 160.2,
        "package": "AlecRabbit\\",
        "pageRank": 0.1,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AlecRabbit\\ConsoleColour",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "force256Colors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "are256ColorsForced",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "are256ColorsSupported",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "areInDocker256ColorsSupported",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "applyEscaped",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "apply",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addTheme",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 7,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 16,
        "ccn": 9,
        "ccnMethodMax": 3,
        "externals": [
            "JakubOnderka\\PhpConsoleColor\\ConsoleColor",
            "parent",
            "AlecRabbit\\ConsoleColour",
            "parent",
            "parent",
            "AlecRabbit\\Exception\\ColorException",
            "parent",
            "AlecRabbit\\Exception\\InvalidStyleException"
        ],
        "parents": [
            "JakubOnderka\\PhpConsoleColor\\ConsoleColor"
        ],
        "lcom": 3,
        "length": 61,
        "vocabulary": 19,
        "volume": 259.12,
        "difficulty": 12.54,
        "effort": 3249.84,
        "level": 0.08,
        "bugs": 0.09,
        "time": 181,
        "intelligentContent": 20.66,
        "number_operators": 18,
        "number_operands": 43,
        "number_operators_unique": 7,
        "number_operands_unique": 12,
        "cloc": 19,
        "loc": 74,
        "lloc": 55,
        "mi": 79.27,
        "mIwoC": 43.93,
        "commentWeight": 35.34,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.88,
        "relativeSystemComplexity": 64.88,
        "totalStructuralComplexity": 512,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 519,
        "package": "AlecRabbit\\",
        "pageRank": 0.29,
        "afferentCoupling": 3,
        "efferentCoupling": 6,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "AlecRabbit\\Exception\\InvalidStyleException",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "AlecRabbit\\Exception\\",
        "pageRank": 0.21,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "AlecRabbit\\Exception\\ColorException",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Exception"
        ],
        "parents": [
            "Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "AlecRabbit\\Exception\\",
        "pageRank": 0.21,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    }
]